# Part of the CODEerts app suite. See LICENSE file for full copyright and licensing details.
{
    'name': 'CODEerts Subscriptions | Odoo Recurring Billing & Invoicing | MRR & Membership Management | SaaS Subscription Manager',
    'summary': 'Recurring billing, automatic subscription invoicing, auto-payment, renewals, upsells, MRR dashboard and customer portal',
    'version': '19.0.1.0.2',
    'category': 'Sales/Subscriptions',
    'author': 'CODEerts',
    'website': 'https://www.codeerts.com',
    'support': 'support@codeerts.com',
    'license': 'OPL-1',
    'depends': [
        'sale_management',
        'account',
        'account_payment',
        'portal',
        'payment',
    ],
    'data': [
        'security/subscription_security.xml',
        'security/ir.model.access.csv',
        'data/subscription_data.xml',
        'data/subscription_cron.xml',
        'wizard/subscription_close_wizard_views.xml',
        'views/subscription_plan_views.xml',
        'views/subscription_close_reason_views.xml',
        'views/subscription_revenue_projection_views.xml',
        'views/subscription_log_views.xml',
        'views/product_template_views.xml',
        'views/sale_order_views.xml',
        'views/portal_templates.xml',
        'views/subscription_menus.xml',
        'views/subscription_dashboard.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'codeerts_subscription/static/src/dashboard/subscription_dashboard.js',
            'codeerts_subscription/static/src/dashboard/subscription_dashboard.xml',
            'codeerts_subscription/static/src/dashboard/subscription_dashboard.scss',
        ],
    },
    'application': True,
    'installable': True,
    'images': ['static/description/banner.gif'],
}
